GET http://localhost:8080/courses
Accept: application/json

###

POST http://localhost:8080/courses
Content-Type: application/json

{
  "startDate": "2022-03-16T11:06:00",
  "endDate": "2022-03-19T11:06:00",
  "name": "New History",
  "students": [
    {"id": 1}
  ],
  "description": "Course about history"
}

###

GET http://localhost:8080/courses/5
Accept: application/json

###

PUT http://localhost:8080/courses/2
Content-Type: application/json

{
  "name": "IT1",
  "description": "Course not about it"
}

###

DELETE http://localhost:8080/courses/2
Accept: application/json

###

GET http://localhost:8080/courses/4/lessons
Accept: application/json

###

POST http://localhost:8080/courses/4/lessons
Content-Type: application/json

{
  "startTime": "2022-03-20T11:06:00",
  "endTime": "2022-03-25T11:06:00",
  "dayOfWeek": "Friday",
  "teacher": {
    "id": 1
  }
}

###

PUT http://localhost:8080/courses/4/lessons/1
Content-Type: application/json

{
  "dayOfWeek": "Sunday"
}

###

DELETE http://localhost:8080/courses/4/lessons/2
Accept: application/json

###

GET http://localhost:8080/courses/5/students
Accept: application/json

###

POST http://localhost:8080/courses/4/students
Content-Type: application/json

{
  "id": "2"
}

###

DELETE http://localhost:8080/courses/4/students/2
Accept: application/json

###

GET http://localhost:8080/courses/2/teachers
Accept: application/json

###

POST http://localhost:8080/courses/2/teachers
Content-Type: application/json

{
  "id": 1
}

###

DELETE http://localhost:8080/courses/2/teachers/1
Accept: application/json