GET http://localhost:8080/users
Accept: application/json

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Dima",
  "lastName": "Savostikov",
  "role": "STUDENT",
  "login": "DimaJco",
  "password": "123"
}

###
PUT http://localhost:8080/users/4
Content-Type: application/json

{
  "firstName": "Vladislav",
  "lastName": "Savostikov",
  "role": "STUDENT",
  "login": "jconcent1",
  "password": "123"
}

###
DELETE http://localhost:8080/users/4
Content-Type: application/json

